spring.application.name=mk-menswear
spring.datasource.url=jdbc:mysql://localhost:3306/db99?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.servlet.session.timeout=2h
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
app.mail.netease.username=15198514656@163.com
app.mail.netease.password=MAnmQ33cjkYFEj8f
app.mail.qq.username=2500327376@qq.com
app.mail.qq.password=muswomntiiecebbi
